package com.chenxing.wms.erp.oa.entity;

import com.chenxing.wms.erp.oa.entity.base.BaseOaEventRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaEventRelation extends BaseOaEventRelation<OaEventRelation> {
	public static final OaEventRelation dao = new OaEventRelation().dao();
}
