package com.chenxing.wms.erp.oa.entity;


import com.chenxing.wms.erp.oa.entity.base.BaseOaExamine;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaExamine extends BaseOaExamine<OaExamine> {
	public static final OaExamine dao = new OaExamine().dao();
}
