package com.chenxing.wms.erp.admin.entity;

import com.chenxing.wms.erp.admin.entity.base.BaseAdminMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminMenu extends BaseAdminMenu<AdminMenu> {
	public static final AdminMenu dao = new AdminMenu().dao();
}
