package com.chenxing.wms.erp.work.entity;

import com.chenxing.wms.erp.work.entity.base.BaseTaskComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaskComment extends BaseTaskComment<TaskComment> {
	public static final TaskComment dao = new TaskComment().dao();
}
