package com.chenxing.wms.erp.crm.entity;


import com.chenxing.wms.erp.crm.entity.base.BaseAdminCustomerSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminCustomerSetting extends BaseAdminCustomerSetting<AdminCustomerSetting> {
	public static final AdminCustomerSetting dao = new AdminCustomerSetting().dao();
}
