package com.chenxing.wms.erp.crm.entity;

import com.chenxing.wms.erp.crm.entity.base.BaseCrmLeads;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmLeads extends BaseCrmLeads<CrmLeads> {
	public static final CrmLeads dao = new CrmLeads().dao();
}
