package com.chenxing.wms.erp.crm.entity;

import com.chenxing.wms.erp.crm.entity.base.BaseCrmProductCategory;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmProductCategory extends BaseCrmProductCategory<CrmProductCategory> {
	public static final CrmProductCategory dao = new CrmProductCategory().dao();

	private List<CrmProductCategory> categories;

	public List<CrmProductCategory> getCategories() {
		return categories;
	}

	public void setCategories(List<CrmProductCategory> categories) {
		this.categories = categories;
	}
}
