package com.chenxing.wms.erp.crm.entity;


import com.chenxing.wms.erp.crm.entity.base.BaseCrmReceivablesPlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmReceivablesPlan extends BaseCrmReceivablesPlan<CrmReceivablesPlan> {
	public static final CrmReceivablesPlan dao = new CrmReceivablesPlan().dao();
}
